### ISSUE TITLE
Training Issues 

### ISSUE THREAD

**Issue by Gaoxinyue423** [HanGuangXin/ByteTrack_ReID#13]
run   python3 tools/train.py -f exps/example/mot/yolox_x_mot17_half.py -d 1 -b 1 --fp16 -o -c pretrained/yolox_x.pth

 ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (16529), thread 'MainThread' (140255758401728):
Traceback (most recent call last):

  File "tools/train.py", line 122, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=1, ckpt='pretrained/yolox_x.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/example/...
         

> File "/home/pc116/Documents/gxy/ByteTrack-main/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ 
    └ <function main at 0x7f8f41687620>

  File "tools/train.py", line 100, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f8e8b7da9d8>
    └ <yolox.core.trainer.Trainer object at 0x7f8f41681b00>

  File "/home/pc116/Documents/gxy/ByteTrack-main/yolox/core/trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7f8f41667ae8>
    └ <yolox.core.trainer.Trainer object at 0x7f8f41681b00>

  File "/home/pc116/Documents/gxy/ByteTrack-main/yolox/core/trainer.py", line 146, in before_train
    no_aug=self.no_aug,
           │    └ False
           └ <yolox.core.trainer.Trainer object at 0x7f8f41681b00>

  File "exps/example/mot/yolox_x_mot17_half.py", line 54, in get_data_loader
    total_ids = dataset.nID         # TODO: total ids for reid classifier
                └ <yolox.data.datasets.mot.MOTDataset object at 0x7f8f16dbc860>

  File "/home/pc116/anaconda3/envs/gxy/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError

AttributeError

**Comment by HanGuangXin** [comment]
total_ids issue. see other issues or setup again.



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 13, 2022 12:55 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [HanGuangXin/ByteTrack_ReID] Training Issues  (Issue #13)




 
run   python3 tools/train.py -f exps/example/mot/yolox_x_mot17_half.py -d 1 -b 1 --fp16 -o -c pretrained/yolox_x.pth
 
ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (16529), thread 'MainThread' (140255758401728):
 Traceback (most recent call last):
 
File "tools/train.py", line 122, in 
 args=(exp, args),
 │    └ Namespace(batch_size=1, ckpt='pretrained/yolox_x.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/example/...
  
File "/home/pc116/Documents/gxy/ByteTrack-main/yolox/core/launch.py", line 90, in launch
 main_func(*args)
 │          └
 └ <function main at 0x7f8f41687620&gt;
  
File "tools/train.py", line 100, in main
 trainer.train()
 │       └ <function Trainer.train at 0x7f8e8b7da9d8&gt;
 └ <yolox.core.trainer.Trainer object at 0x7f8f41681b00&gt;
 
File "/home/pc116/Documents/gxy/ByteTrack-main/yolox/core/trainer.py", line 70, in train
 self.before_train()
 │    └ <function Trainer.before_train at 0x7f8f41667ae8&gt;
 └ <yolox.core.trainer.Trainer object at 0x7f8f41681b00&gt;
 
File "/home/pc116/Documents/gxy/ByteTrack-main/yolox/core/trainer.py", line 146, in before_train
 no_aug=self.no_aug,
 │    └ False
 └ <yolox.core.trainer.Trainer object at 0x7f8f41681b00&gt;
 
File "exps/example/mot/yolox_x_mot17_half.py", line 54, in get_data_loader
 total_ids = dataset.nID         # TODO: total ids for reid classifier
 └ <yolox.data.datasets.mot.MOTDataset object at 0x7f8f16dbc860&gt;
 
File "/home/pc116/anaconda3/envs/gxy/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 83, in getattr
 raise AttributeError
 
AttributeError

**Comment by HanGuangXin** [comment]
I am closing this issue, re-open it if you had other questions.
