### ISSUE TITLE
Training MOT17 and MOT20 together 

### ISSUE THREAD

**Issue by abhigoku10** [HanGuangXin/ByteTrack_ReID#16]
@HanGuangXin  thanks for sharing the codebase i have couple of queries 
When i am training for mix dataset of MOT17 and MOT20 i am getting an error  shoudl i use the same scrip provide by you or should changes be made in the code 

THanks in advance

**Comment by HanGuangXin** [comment]
I need more information about the error.

**Comment by abhigoku10** [comment]
@HanGuangXin 
!python3 /tools/train.py -f /exps/example/mot/yolox_x_ablation.py -d 1 -b 1 --fp16 -o -c pretrained/yolox_x.pth.tar
 2022-04-21 07:45:47 | INFO     | yolox.data.datasets.mot:39 - loading annotations into memory...
2022-04-21 07:45:47 | INFO     | yolox.data.datasets.mot:39 - Done (t=0.00s)
2022-04-21 07:45:47 | INFO     | pycocotools.coco:88 - creating index...
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
2022-04-21 07:45:47 | INFO     | pycocotools.coco:88 - index created!
2022-04-21 07:45:47 | INFO     | yolox.data.datasets.mot:39 - loading annotations into memory...
2022-04-21 07:45:47 | INFO     | yolox.data.datasets.mot:39 - Done (t=0.01s)
2022-04-21 07:45:47 | INFO     | pycocotools.coco:88 - creating index...
2022-04-21 07:45:47 | INFO     | pycocotools.coco:88 - index created!
2022-04-21 07:45:47 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (972), thread 'MainThread' (140251810465664):
Traceback (most recent call last):

  File "/gdrive/MyDrive/ByteTrack/ByteTrack_HOME/ByteTrack_ReID/tools/train.py", line 122, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=1, ckpt='/gdrive/MyDrive/ByteTrack/ByteTrack_HOME/pretrained/yolox_x.pth.tar', devices=1, dist_backend='...
          └ ╒══════════════════╤════════════════════════════════════════════════════════════════════════════════╕
            │ keys             │ va...

> File "/gdrive/MyDrive/ByteTrack/ByteTrack_HOME/ByteTrack_ReID/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys             │ v...
    └ <function main at 0x7f8ee9310d40>

  File "/gdrive/MyDrive/ByteTrack/ByteTrack_HOME/ByteTrack_ReID/tools/train.py", line 100, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f8dcd07d950>
    └ <yolox.core.trainer.Trainer object at 0x7f8dc804d050>

  File "/gdrive/MyDrive/ByteTrack/ByteTrack_HOME/ByteTrack_ReID/yolox/core/trainer.py", line 75, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7f8dcc21b5f0>
    └ <yolox.core.trainer.Trainer object at 0x7f8dc804d050>

  File "/gdrive/MyDrive/ByteTrack/ByteTrack_HOME/ByteTrack_ReID/yolox/core/trainer.py", line 157, in before_train
    model = self.exp.get_model(settings=self.settings)
            │    │   │                  │    └ {}
            │    │   │                  └ <yolox.core.trainer.Trainer object at 0x7f8dc804d050>
            │    │   └ <function Exp.get_model at 0x7f8dc8069ef0>
            │    └ ╒══════════════════╤════════════════════════════════════════════════════════════════════════════════╕
            │      │ keys             │ va...
            └ <yolox.core.trainer.Trainer object at 0x7f8dc804d050>

  File "/gdrive/MyDrive/ByteTrack/ByteTrack_HOME/ByteTrack_ReID/yolox/exp/yolox_base.py", line 74, in get_model
    nID = settings['total_ids']
          └ {}

KeyError: 'total_ids'

**Comment by HanGuangXin** [comment]
https://github.com/HanGuangXin/ByteTrack_ReID/issues/13#issue-1202756264

**Comment by HanGuangXin** [comment]
Check the code about `total_ids`, I don't think it will take you much time :)
