### ISSUE TITLE
Got an error when evaluating and testing the model trained with this code

### ISSUE THREAD

**Issue by NaifahNurya** [HanGuangXin/ByteTrack_ReID#2]
Thanks for this work, 
The training was successful, however I got an error  when I tried to test (demo on video) and evaluating (for performance evaluation like MOTA, IDS etc)

1. The following is an error when I do demo (on video)

```
[warning] No nID got!!!
2022-01-24 10:28:34.520 | INFO     | __main__:main:326 - Model Summary: Params: 104.65M, Gflops: 880.83
2022-01-24 10:28:34.524 | INFO     | __main__:main:334 - loading checkpoint
Traceback (most recent call last):
  File "tools/demo_track.py", line 372, in <module>
    main(exp, args)
  File "tools/demo_track.py", line 337, in main
    model.load_state_dict(ckpt["model"])
  File "C:\Users\admin\anaconda3\envs\bytetrack_reid\lib\site-packages\torch\nn\modules\module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for head.reid_classifier.weight: copying a param with shape torch.Size([40, 128]) from checkpoint, the shape in current model is torch.Size([2, 128]).
        size mismatch for head.reid_classifier.bias: copying a param with shape torch.Size([40]) from checkpoint, the shape in current model is torch.Size([2]).

```

Is there any modification needed in the code. In [40, 128], 40 in the number of id trained in my model. 

2. The following is an error when I do evaluation

```
> File "c:\users\admin\desktop\bytetrack_Reid\yolox\core\launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x000001C75DE9F3A0>

  File "tools\track.py", line 220, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function MOTEvaluator.evaluate at 0x000001C75D08C280>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x000001C714D7D5B0>

  File "c:\users\admin\desktop\bytetrack_Reid\yolox\evaluators\mot_evaluator.py", line 137, in evaluate
    frame_id = info_imgs[2].item()
               └ [tensor([1080]), tensor([1545]), ['MOT20-04/img1/000001.jpg']]

AttributeError: 'list' object has no attribute 'item'

```

Thank you.

**Comment by NaifahNurya** [comment]
Any updates @HanGuangXin ,

**Comment by NaifahNurya** [comment]
@HanGuangXin 

I managed to solve the first problem (When doing demo on video). I modify the file demo_track.py, by adding code related to re-id.

However, with problem 2 (during evaluation in mot20 or other custom dataset) still got the following error.

```
Traceback (most recent call last):

  File "tools\track.py", line 290, in <module>
    launch(
    └ <function launch at 0x000001BC9F33A5E0>

> File "c:\users\admin\desktop\byteTrack_reid\yolox\core\launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001BCAD110550>

  File "tools\track.py", line 167, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(batch_size=1, ckpt='pretrained/best_ckpt.pth.tar', conf=0.01, devices=1, dist_backend='nccl', dist_url=None, exp_fi...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(batch_size=1, ckpt='pretrained/best_ckpt.pth.tar', conf=0.01, devices=1, dist_backend='nccl', dist_url=None, exp_fi...
                 │   └ <function Exp.get_eval_loader at 0x000001BCAD110DC0>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "C:\Users\admin\Desktop\ByteTrack_reid\exps/example/mot\yolox_x_mot17_half.py", line 100, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "c:\users\admin\desktop\byteTrack_reid\yolox\data\datasets\mot.py", line 48, in __init__
    self.nID = self.get_total_ids()         # TODO: total ids for reid classifier
    │          │    └ <function MOTDataset.get_total_ids at 0x000001BCA03C3820>
    │          └ <yolox.data.datasets.mot.MOTDataset object at 0x000001BCE571F7C0>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x000001BCE571F7C0>

  File "c:\users\admin\desktop\byteTrack_reid\yolox\data\datasets\mot.py", line 140, in get_total_ids
    max_id_each_img.append(int(max(res[:, 5])))
    │               │              └ array([], shape=(0, 6), dtype=float64)
    │               └ <method 'append' of 'list' objects>
    └ []

ValueError: max() arg is an empty sequence
```

Any suggestion on solving this issue.

Thank you.

**Comment by HanGuangXin** [comment]
Here is the thing. ReID task in MOT is usually treated as a classification task, with track_ids as the class. So `get_total_ids()` is a function that calculate the total ids in the dataset.

So you maybe should modify the function  `get_total_ids()` to calculate the total ids in the dataset corresponding datasets.

@NaifahNurya

**Comment by HanGuangXin** [comment]
And the reason of 'size mismatch error' is that in YOLOX, head network and loss calculation is in **one** Class, so the ReID classifier has to be initialized even if we don't use it when evaluating.

So during evaluation, you should delete parameters of classifier and set `strict=False` when loading checkpoints. Code can be found in `tools/track.py`.

@NaifahNurya

**Comment by abhigoku10** [comment]
@NaifahNurya thanks for sharing your progress i have couple of queries 
1. which dataset did u train it on MOT20 or MOT17 ?
2. Can you please share your pretrained model as i am facing issues during dataload while training 

THanks in adance

**Comment by HanGuangXin** [comment]
@abhigoku10 
The model is trained on MOT17, see `yolox_s_mot17_half.py` for more information.
Trained model will be updated soon, or you can train it yourself.
